version: '2.1'

services:
  db:
    image: mariadb:10.5
    container_name: gra_db
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=itsASecret
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=gra
      - MYSQL_PASSWORD=test123
      - MYSQL_DATABASE=gradb
    logging:       
      driver:   "json-file"
      options:  
        max-size: "30m"
        max-file: "5"
  
      
  gra:
    image: onap/sdnc-gra-image:latest
    depends_on:
      - db
    container_name: gra_controller
    ports:
      - "8080:8080"
      - "8443:8443"
    links:
      - db:dbhost
    environment:
      - MYSQL_DB_HOST=dbhost
      - MYSQL_ROOT_PASSWORD=itsASecret
      - MYSQL_USER=gra
      - MYSQL_PASSWORD=test123
      - MYSQL_DATABASE=gradb
      - LOG_LEVEL=TRACE
      - TRUSTSTORE_PASSWORD=changeit
      - CACERT_PASSWORD=changeit
      - SDNC_CERT_DIR=/opt/onap/sdnc/config
      - JAVA_SECURITY_DIR=/usr/lib/jvm/default-jvm/jre/lib/security
      - TRUSTSTORE=truststoreONAPall.jks
    volumes:
      - ../resources:/opt/onap/sdnc/config
    logging:       
      driver:   "json-file"
      options:  
        max-size: "30m"
        max-file: "5"
    extra_hosts:
      aaf-onap-test.osaaf.org: 10.12.5.145

  dgbuilder:
    image: onap/ccsdk-dgbuilder-image:latest
    depends_on:
      - db
    container_name:  gra_dgbuilder
    entrypoint:
       - "/bin/bash"
       - "-c"
       - "cd /opt/onap/ccsdk/dgbuilder/ && ./start.sh sdnc1.0 && wait"
    ports:
      - "3200:3100"
    volumes:
      - ${HOME}/gerrit/sdnc/oam/platform-logic:/opt/onap/ccsdk/platform-logic
    links:
      - db:dbhost
      - db:sdnctldb01
      - db:sdnctldb02
    environment:
      - MYSQL_ROOT_PASSWORD=itsASecret
      - SDNC_CONFIG_DIR=/opt/onap/ccsdk/data/properties
      - MYSQL_USER=gra
      - MYSQL_PASSWORD=test123
      - MYSQL_DATABASE=gradb
    logging:       
      driver:   "json-file"
      options:  
        max-size: "30m"
        max-file: "5"
