version: '2.1'

services:
  db:
    image: dockercentral.it.att.com:5100/com.att.sdncp/mysql-image:latest
    container_name: gra_db
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    logging:
      driver:   "json-file"
      options:
        max-size: "30m"
        max-file: "5"


  gra:
    image: dockercentral.it.att.com:5100/com.att.sdncp/generic-resource-api:latest
    depends_on:
      - db
    container_name: gra_controller
    ports:
      - "8181:8080"
      - "8443:8443"
    volumes:
      - ../resources/application.properties:/opt/sdnc/gra/config/application.properties
     # Uncomment line below to authenticate with AAF
     # - ../resources/cadi-example.properties:/opt/sdnc/gra/config/cadi.properties
      - ../resources/cadi-log.properties:/opt/sdnc/gra/config/cadi-log.properties
    links:
      - db:dbhost
    environment:
      - MYSQL_DB_HOST=dbhost
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - ODL_USER=${ODL_USER}
      - AAF_MECHID_CRED=${ODL_PASSWORD}
      - ODL_URI=http://localhost:8080
      - SDNC_CONFIG_DIR=/opt/sdnc/gra/config
      - LOG_LEVEL=DEBUG
      - TRUSTSTORE_PASSWORD=changeit
      - CACERT_PASSWORD=changeit
      - SDNC_CERT_DIR=/opt/sdnc/gra/config
      - JAVA_SECURITY_DIR=/usr/lib/jvm/default-jvm/jre/lib/security
      - TRUSTSTORE=truststoreONAPall.jks
      - SDNNFT_HOST=${SDNNFT_HOST:-localhost}
      - LOG_PATH=/opt/sdnc/gra/logs
    logging:
      driver:   "json-file"
      options:
        max-size: "30m"
        max-file: "5"
    extra_hosts:
      aaf-onap-test.osaaf.org: 10.12.5.145

  dgbuilder:
    image: nexus3.onap.org:10001/onap/ccsdk-dgbuilder-image:latest
    depends_on:
      - db
    container_name:  gra_dgbuilder
    entrypoint:
       - "/bin/bash"
       - "-c"
       - "cd /opt/onap/ccsdk/dgbuilder/ && ./start.sh sdnc1.0 && wait"
    ports:
      - "3200:3100"
    volumes:
      - ${HOME}/st_sdncp/platform-logic:/opt/onap/ccsdk/platform-logic
    links:
      - db:dbhost
      - db:sdnctldb01
      - db:sdnctldb02
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SDNC_CONFIG_DIR=/opt/onap/ccsdk/data/properties
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    logging:
      driver:   "json-file"
      options:
        max-size: "30m"
        max-file: "5"
